<a href="https://colab.research.google.com/github/konarksharma2001/pthon/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
A = [1,2,3]
print(type(A))
print(A)

<class 'list'>
[1, 2, 3]


In [3]:
Arr_A = np.array(A)
print(type(Arr_A))
print(Arr_A)

<class 'numpy.ndarray'>
[1 2 3]


In [4]:
Lol = [[1,1,1],[2,2,2],[3,3,3]]
print(Lol)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]


In [5]:
np.array(Lol)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [7]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,20,4)

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [15]:
np.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#RANDOM DISTRIBUTION

In [87]:
np.random.rand(1)

array([0.70807258])

In [21]:
np.random.randn(5)

array([ 0.88989301, -1.56486876,  0.8536136 ,  0.92125514, -0.28426644])

In [88]:
np.random.randint(0,10,3)

array([5, 4, 1])

In [89]:
np.random.randint(0,50,(4,5))

array([[23, 43, 29, 37,  1],
       [20, 32, 11, 21, 43],
       [24, 48, 26, 41, 27],
       [15, 14, 46, 43,  2]])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
A = np.arange(0,25)

In [26]:
A.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
#A.reshape(5,3) prints error

In [90]:
Randarr = np.random.randint(0,51,8)
Randarr

array([36, 50,  6, 20,  8, 38, 17,  3])

In [91]:
Randarr.max()

50

In [92]:
Randarr.min()

3

In [93]:
Randarr.argmax()

1

In [34]:
Randarr.dtype

dtype('int64')

In [94]:
A.shape

(1, 25)

In [95]:
A = A.reshape(5,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
A.shape

(5, 5)

In [39]:
A = A.reshape(1,25)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

#Indexing and Selection

In [40]:
arr = np.arange(0,15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr[4]

4

In [42]:
arr[4:9]

array([4, 5, 6, 7, 8])

In [43]:
arr[0:4]

array([0, 1, 2, 3])

In [44]:
arr[:4] # considers by default start index as 0

array([0, 1, 2, 3])

#Broadcasting

In [45]:
arr[9:]=100
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100, 100, 100, 100,
       100, 100])

In [46]:
slicingarray = arr[1:6]
slicingarray

array([1, 2, 3, 4, 5])

In [48]:
slicingarray[:]=100
slicingarray

array([100, 100, 100, 100, 100])

In [49]:
arr

array([  0, 100, 100, 100, 100, 100,   6,   7,   8, 100, 100, 100, 100,
       100, 100])

#Indexing and Selection in 2D

In [50]:
array2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
array2D.shape

(3, 3)

In [53]:
array2D[0]

array([1, 2, 3])

In [54]:
array2D[2]

array([7, 8, 9])

In [55]:
print(array2D[1][2])

6


In [56]:
array2D[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
array2D[:2,1:]

array([[2, 3],
       [5, 6]])

In [58]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
bool_array = a>5
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [62]:
a[bool_array]

array([ 6,  7,  8,  9, 10])

In [63]:
a[a>5]

array([ 6,  7,  8,  9, 10])

#NUMPY OPERATIONS

In [64]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [66]:
a -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [67]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
a * a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
a/a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/a

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [72]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
a.sum()

45

In [76]:
a.max()

9

In [78]:
a.mean()

4.5

In [79]:
a.var()

8.25

In [81]:
a2D = np.arange(0,25).reshape(5,5)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a2D.sum()

300

In [85]:
a2D.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [86]:
a2D.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

#Vectorization

In [96]:
a = np.array([1,2,3,4])     #This is how to declare a 1D array
print(a)
#numpy.random.rand() method creates array of specified shape with random values.
b = np.random.rand(5)       #Generating 5 random values
print(b)

[1 2 3 4]
[0.94220176 0.56328822 0.3854165  0.01596625 0.23089383]


In [97]:

import time

a = np.random.rand(10000000)       #a is 1D array of 10 Million Random Values
b = np.random.rand(10000000)


###Comparing the time taken for dot product of a and b vectors in milliseconds

In [99]:

tic = time.time()
c   = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized Version:"+str(1000*(toc-tic))+"ms")
c=0
tic = time.time()
for i in range(10000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For Loop Version:"+str(1000*(toc-tic))+"ms")

2499546.4332769495
Vectorized Version:29.006481170654297ms
2499546.4332771967
For Loop Version:6163.435935974121ms


#PANDAS

In [100]:
import numpy as np
import pandas as pd

In [104]:
#help(pd.Series)
#pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

In [102]:

myindex = ['India', 'USA', 'Canada']
mydata = [1947, 1776, 1867]

In [103]:
myseries = pd.Series(data = mydata)
myseries

0    1947
1    1776
2    1867
dtype: int64

In [105]:
type(myseries)

pandas.core.series.Series

In [106]:
myseries = pd.Series(data = mydata, index = myindex)
myseries


India     1947
USA       1776
Canada    1867
dtype: int64

In [107]:
print(myseries[0])
print(myseries['India'])

1947
1947


##Series Operations

In [108]:
#Performance of Mumbai Indians in IPL Matches
Match1 = {'Rohit':80, 'SKY': 68, 'Pollard': 90, 'Ishan': 45}
Match2 = {'Rohit':100, 'SKY': 80, 'Pollard': 20, 'Ishan': 60}

In [109]:
series_m1 = pd.Series(Match1)
series_m2 = pd.Series(Match2)

In [110]:
series_m1


Rohit      80
SKY        68
Pollard    90
Ishan      45
dtype: int64

In [111]:
series_m2


Rohit      100
SKY         80
Pollard     20
Ishan       60
dtype: int64

In [112]:
series_m1.keys()


Index(['Rohit', 'SKY', 'Pollard', 'Ishan'], dtype='object')

In [113]:
#Broadcasted operation on series
[1, 2] * 2

[1, 2, 1, 2]

In [114]:

np.array([1, 2])*2

array([2, 4])

In [115]:

(series_m1*2)/10


Rohit      16.0
SKY        13.6
Pollard    18.0
Ishan       9.0
dtype: float64

In [116]:
series_m1['Pandya'] = 40   #append values
series_m2['Bumrah'] = 10
print(series_m1)
print(series_m2)

Rohit      80
SKY        68
Pollard    90
Ishan      45
Pandya     40
dtype: int64
Rohit      100
SKY         80
Pollard     20
Ishan       60
Bumrah      10
dtype: int64


In [117]:
series_m1 + series_m2

Bumrah       NaN
Ishan      105.0
Pandya       NaN
Pollard    110.0
Rohit      180.0
SKY        148.0
dtype: float64

In [118]:
op = series_m1.add(series_m2, fill_value=0)
op

Bumrah      10.0
Ishan      105.0
Pandya      40.0
Pollard    110.0
Rohit      180.0
SKY        148.0
dtype: float64

In [119]:
op.dtype

dtype('float64')

#Data Frames

In [120]:
np.random.seed(100)
mydata = np.random.randint(0, 101, (3,4))
mydata

array([[ 8, 24, 67, 87],
       [79, 48, 10, 94],
       [52, 98, 53, 66]])

In [121]:

myindex = ['Mumbai','Delhi','Hyderabad']
mycolumns = ['Jan','Feb','Mar','Apr']

In [122]:

df = pd.DataFrame(mydata)
df

0   1   2   3
0   8  24  67  87
1  79  48  10  94
2  52  98  53  66

In [123]:
df = pd.DataFrame(data = mydata, index = myindex)
df      #Multi-Index Rows without Column name

0   1   2   3
Mumbai      8  24  67  87
Delhi      79  48  10  94
Hyderabad  52  98  53  66

In [124]:
df = pd.DataFrame(data = mydata, index = myindex, columns = mycolumns)
df

Jan  Feb  Mar  Apr
Mumbai       8   24   67   87
Delhi       79   48   10   94
Hyderabad   52   98   53   66

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Mumbai to Hyderabad
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     3 non-null      int64
 1   Feb     3 non-null      int64
 2   Mar     3 non-null      int64
 3   Apr     3 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


###Reading Files

In [ ]:
#df = pd.read_csv

In [126]:
!pwd #preaent working directory

/content


In [127]:
!ls

sample_data


In [128]:
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]